# Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57
cartesian_limits:
  max_trans_vel: 0.5
  max_trans_acc: 0.5
  max_trans_dec: -0.5
  max_rot_vel: 0.5
